### ISSUE TITLE
Terminologija

### ISSUE THREAD

**Issue by jaanos** [MancaStrgar/-Fractional-chromatic-number-and-fractional-clique-number-of-a-graph#1]
Opažam, da sta *fractional chromatic/clique number* prevajala kot *delno kromatično/klično število*. Po posvetovanju s prof. Škrekovskim predlagam, da namesto *delno* uporabita izraz *deljeno*. *Fractional* se namreč sklicuje na to, da je to število lahko ulomek (v nasprotju z običajnim kromatičnim ali kličnim številom, ki je naravno število). Poleg tega deljeno kromatično število pride iz optimalnega *deljenega bavanja* - torej takega barvanja, kjer vsako vozlišče razdelimo na več barv.

**Comment by MancaStrgar** [comment]
Sva popravila in novo verzijo naložila na git.
